### TOPIC:
### PCA

library(mvtnorm)
library(mvnormtest)
library(car) 

################# Exploratory analysis ##################
# Boxplot
x11()
boxplot(d, las=1, col='red', main='Boxplot',grid=T)

# Boxplot with outliers (requires CAR)
x11()
Boxplot(d, id.method="y")

# Matplot + boxplot
x11()
matplot(t(d), type='l', axes=F)
box()
boxplot(d, add=T, boxwex=0.1, col='red')


# If variability changes too much with variables
d <- scale(d)





################# PCA ##################
pca <- princomp(d, scores=T)
pca 
summary(pca)


# Plot original vs pca vs var explained
# Set ylim in barplots consistently with yout data
x11()
layout(matrix(c(2,3,1,3),2,byrow=T))
barplot(pca$sdev^2, las=2, main='Principal components', ylim=c(0,10), ylab='Variances')
barplot(sapply(d,sd)^2, las=2, main='Original variables', ylim=c(0,5), ylab='Variances')
plot(cumsum(pca$sdev^2)/sum(pca$sdev^2), type='b', axes=F, xlab='number of components', 
     ylab='contribution to the total variability', ylim=c(0,1))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(d),labels=1:ncol(d),las=2)






################# SCORES AND LOADING INTERPR PLOT ##################
# Scores
scores <- pca$scores

x11()
layout(matrix(c(1,2),1,2))
boxplot(d, las=2, col='red', main='Variabili originarie')
boxplot(scores, las=2, col='red', main='Componenti principali')

x11()
Boxplot(d, id.method="y",las=2, col='red', main='Variabili originarie')
Boxplot(scores, id.method="y",las=2, col='red', main='Componenti principali')



# Loadings
load <- pca$loadings
a = 4 # number of principal components to be interpreted, change accordingly

x11()
par(mar = c(1,4,0,2), mfrow = c(a,1))
for(i in 1:a)
  barplot(load[,i], ylim = c(-1, 1))

# filter the most significant loadings
x11()
par(mar = c(1,4,0,2), mfrow = c(a,1))
for(i in 1:a) barplot(ifelse(abs(load[,i]) < 0.3, 0, load[,i]) , ylim = c(-1, 1));abline(h=0)







################# BIPLOT AND PROJ ON SPACE GENERATED BY FIRST k-(th) PC ##################
# Biplot
x11()
biplot(pca, scale=0, cex=.7)

# Projection on the space generated by the k-th principal component
x11(width=21, height=7)
par(mfrow=c(2,3))
matplot(t(d), type='l', main = 'Data', ylim=range(d))

meanF <- colMeans(d)
matplot(meanF, type='l', main = '0 PC', lwd=2, ylim=range(d))
for(i in 1:a)
{
  projection <- matrix(meanF, dim(d)[[1]], dim(d)[[2]], byrow=T) + scores[,i] %*% t(load[,i])
  matplot(t(projection), type='l', main = paste(i, 'PC'), ylim=range(d))
  matplot(meanF, type='l', lwd=2, add=T)
}


# Projection on the space generated by the first k principal components
x11(width=21, height=7)
par(mfrow=c(2,3))
matplot(t(d), type='l', main = 'Data', ylim=range(d))
meanF <- colMeans(d)
matplot(meanF, type='l', main = 'First 0 PCs', lwd=2, ylim=range(d))
projection <- matrix(meanF, dim(d)[[1]], dim(d)[[2]], byrow=T)
for(i in 1:a)
{
  projection <- projection + scores[,i] %*% t(load[,i])
  matplot(t(projection), type='l', main = paste('First', i, 'PCs'), ylim=range(d))
  matplot(meanF, type='l', lwd=2, add=T)
}





################# NEW DATA PROJ ON PC ##################

x.mean <- colMeans(d)
x.var <- sapply(d, FUN = sd)

new <- c(
    Energy_kcal=400,
    Protein_g=9,
    Fat_g=5,
    Carb_g=100,
    Sugar_g=30,
    Fiber_g=4
)

new <- (new - x.mean) / x.var

pc.proj <- new %*% pca$loadings[,1:2]
pc.proj

par(mfrow=c(1,1))
plot(pca$scores)
points(pc.proj, col=2, pch=16, cex=2)





